name: Build binary

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: rustup update
      - name: Setup VS (Windows)
        uses: microsoft/setup-msbuild@v1.1
        if: matrix.os == 'windows-latest'
      - name: Build
        run: cargo build --release --verbose
